
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: glpi-pvc
  labels:
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: glpi-pv
  storageClassName: local-storage
  volumeMode: Filesystem 
---



